### PR TITLE
Update drows.c

### PR DESCRIPTION
**Pull request by bluethenix**
Fixed a grammer typo and removed a seemingly superfluous old comment above the xp line that only added confusion. I expect there will be some issues as this is my first attempt. Please let me know.

### CODE REVIEW

**Comment by facadepapergirl** [comment]
You have "They follow their orders without question with no questions asked."
There should be a comma or an and at the end of the first "question", but the second part should probably just be deleted to remove the repetitive statement.

**Comment by bluethenix** [comment]
Should be fixed now. How does it look? @facadepapergirl

**Comment by facadepapergirl** [comment]
It looks excellent. I'm no git expert, but it looks like both commits are part of the same pull request.

**Comment by bluethenix** [comment]
Thanks.

**Pull request merged**
